
server:
  shutdown: graceful
  port: 18080

spring:

  profiles:
    include: aws

  lifecycle:
    timeout-per-shutdown-phase: 20s

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver


  flyway:
    user: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    schemas: gift_db
    url: ${LOCAL_DB_URL}
    enabled: true

#  messages:
#    basename: messages, errors

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

logging:
  config: classpath:logback-local.xml
  level:
    org:
      hibernate.SQL: debug
      hibernate.type: trace

example.order:
  base-url: http://localhost:8080/
