version: "3.7"
services:
  gift-db:
    image: mariadb
    ports:
      - "13306:3306"
    environment:
      - MYSQL_DATABASE=gift_db
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_USER_PASSWORD}
      - TZ=UTC
    command: # 명령어 실행
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mariadb:/var/lib/mysql
    restart: always